//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiAnomalyInstaller.AppConstants.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiAnomalyInstaller.AppConstants.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка!\n{0}.
        /// </summary>
        public static string alert_error_text {
            get {
                return ResourceManager.GetString("alert_error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string alert_error_title {
            get {
                return ResourceManager.GetString("alert_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы отменили операцию.
        /// </summary>
        public static string mw_alert_operation_cancelled {
            get {
                return ResourceManager.GetString("mw_alert_operation_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string mw_button_cancel {
            get {
                return ResourceManager.GetString("mw_button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string mw_button_exit {
            get {
                return ResourceManager.GetString("mw_button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string mw_button_install {
            get {
                return ResourceManager.GetString("mw_button_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string mw_button_play {
            get {
                return ResourceManager.GetString("mw_button_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string mw_button_settings {
            get {
                return ResourceManager.GetString("mw_button_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string mw_button_update {
            get {
                return ResourceManager.GetString("mw_button_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подождите....
        /// </summary>
        public static string mw_common_wait {
            get {
                return ResourceManager.GetString("mw_common_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка {0} ({1} % \ {2} из {3}, {4}/s \ {5}).
        /// </summary>
        public static string mw_progress_title_download {
            get {
                return ResourceManager.GetString("mw_progress_title_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финализация....
        /// </summary>
        public static string mw_progress_title_finalization {
            get {
                return ResourceManager.GetString("mw_progress_title_finalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка {0}.
        /// </summary>
        public static string mw_progress_title_hash {
            get {
                return ResourceManager.GetString("mw_progress_title_hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для установки доступна версия {0}.
        /// </summary>
        public static string mw_progress_title_install_available {
            get {
                return ResourceManager.GetString("mw_progress_title_install_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово к запуску.
        /// </summary>
        public static string mw_progress_title_play_available {
            get {
                return ResourceManager.GetString("mw_progress_title_play_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распаковка {0} ({1} %).
        /// </summary>
        public static string mw_progress_title_unpack {
            get {
                return ResourceManager.GetString("mw_progress_title_unpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно обновление! {0} =&gt; {1}.
        /// </summary>
        public static string mw_progress_title_update_available {
            get {
                return ResourceManager.GetString("mw_progress_title_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string sw_button_exit {
            get {
                return ResourceManager.GetString("sw_button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string sw_button_save {
            get {
                return ResourceManager.GetString("sw_button_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НОВЫЙ ПРОФИЛЬ.
        /// </summary>
        public static string sw_profile_new {
            get {
                return ResourceManager.GetString("sw_profile_new", resourceCulture);
            }
        }
    }
}
