//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiAnomalyInstaller.AppConstants.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiAnomalyInstaller.AppConstants.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить Ярлык.
        /// </summary>
        public static string mw_additionally_create_shortcut {
            get {
                return ResourceManager.GetString("mw_additionally_create_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На Рабочий Стол.
        /// </summary>
        public static string mw_additionally_create_shortcut_on_desktop {
            get {
                return ResourceManager.GetString("mw_additionally_create_shortcut_on_desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить Все.
        /// </summary>
        public static string mw_additionally_delete_all {
            get {
                return ResourceManager.GetString("mw_additionally_delete_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить Архивы.
        /// </summary>
        public static string mw_additionally_delete_archives {
            get {
                return ResourceManager.GetString("mw_additionally_delete_archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить Игру.
        /// </summary>
        public static string mw_additionally_delete_game {
            get {
                return ResourceManager.GetString("mw_additionally_delete_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть Лог-Файл.
        /// </summary>
        public static string mw_additionally_open_file_log {
            get {
                return ResourceManager.GetString("mw_additionally_open_file_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку Organizer.
        /// </summary>
        public static string mw_additionally_open_folder_organizer {
            get {
                return ResourceManager.GetString("mw_additionally_open_folder_organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку Storage.
        /// </summary>
        public static string mw_additionally_open_folder_storage {
            get {
                return ResourceManager.GetString("mw_additionally_open_folder_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку Vanilla.
        /// </summary>
        public static string mw_additionally_open_folder_vanilla {
            get {
                return ResourceManager.GetString("mw_additionally_open_folder_vanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred!
        ///Please contact the developer.
        ///---
        ///{0}.
        /// </summary>
        public static string mw_alert_error {
            get {
                return ResourceManager.GetString("mw_alert_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection available!
        ///Further operation of the application is impossible..
        /// </summary>
        public static string mw_alert_internet_unavailable {
            get {
                return ResourceManager.GetString("mw_alert_internet_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.
        /// </summary>
        public static string mw_alert_operation_cancelled {
            get {
                return ResourceManager.GetString("mw_alert_operation_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно этого хотите?.
        /// </summary>
        public static string mw_alert_question_delete {
            get {
                return ResourceManager.GetString("mw_alert_question_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string mw_button_cancel {
            get {
                return ResourceManager.GetString("mw_button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string mw_button_exit {
            get {
                return ResourceManager.GetString("mw_button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string mw_button_install {
            get {
                return ResourceManager.GetString("mw_button_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string mw_button_play {
            get {
                return ResourceManager.GetString("mw_button_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string mw_button_settings {
            get {
                return ResourceManager.GetString("mw_button_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string mw_button_update {
            get {
                return ResourceManager.GetString("mw_button_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string mw_common_wait {
            get {
                return ResourceManager.GetString("mw_common_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling current operation... Please wait....
        /// </summary>
        public static string mw_progress_title_cancelling {
            get {
                return ResourceManager.GetString("mw_progress_title_cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0} ({1}% \ {2} of {3}, {4}/s \ {5}).
        /// </summary>
        public static string mw_progress_title_download {
            get {
                return ResourceManager.GetString("mw_progress_title_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing....
        /// </summary>
        public static string mw_progress_title_finalization {
            get {
                return ResourceManager.GetString("mw_progress_title_finalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying {0}.
        /// </summary>
        public static string mw_progress_title_hash {
            get {
                return ResourceManager.GetString("mw_progress_title_hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version {0}; Required space: {1}.
        /// </summary>
        public static string mw_progress_title_install_available {
            get {
                return ResourceManager.GetString("mw_progress_title_install_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy!.
        /// </summary>
        public static string mw_progress_title_play_available {
            get {
                return ResourceManager.GetString("mw_progress_title_play_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking {0} ({1}%).
        /// </summary>
        public static string mw_progress_title_unpack {
            get {
                return ResourceManager.GetString("mw_progress_title_unpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available! {0} =&gt; {1}.
        /// </summary>
        public static string mw_progress_title_update_available {
            get {
                return ResourceManager.GetString("mw_progress_title_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection available!
        ///Further operation of the application is impossible..
        /// </summary>
        public static string throw_internet_unavailable {
            get {
                return ResourceManager.GetString("throw_internet_unavailable", resourceCulture);
            }
        }
    }
}
